/*
 * vphoned_motion — shake gesture via Mach injection of a helper dylib.
 *
 * Flow on `{"t":"shake"}`:
 *   1. Enumerate running user apps (proc_listpids + path filter), drop the
 *      ones task_for_pid rejects (system apps with get-task-allow=false),
 *      pick the most-foreground one by BKSApplicationStateMonitor state.
 *   2. Resolve the target's data container via LSApplicationWorkspace and
 *      deploy the embedded helper dylib into <container>/tmp/. That's the
 *      only path guaranteed readable by a sandboxed app.
 *   3. task_for_pid + mach_vm_allocate code/path/stack/args in target.
 *   4. thread_create_running runs the OUTER shellcode on a raw Mach thread,
 *      which calls pthread_create_from_mach_thread to spawn an INNER pthread.
 *      The inner has proper TLS, so it can safely call dlopen(path, RTLD_NOW)
 *      — calling dlopen directly from a raw Mach thread crashes inside
 *      pthread_getspecific.
 *   5. After inject, send SIGUSR2 to fire the shake. Works for both fresh
 *      loads (constructor installed the handler) and cached dlopens (handler
 *      from a prior load is still resident).
 *   6. Subsequent shakes for the same pid skip inject and just SIGUSR2.
 *
 * Shellcode uses paciza / blraaz, which authenticate as PAC ops on arm64e
 * and act as NOP+BLR on arm64 — same bytes work for both target ABIs.
 */

#import "vphoned_motion.h"
#import "vphoned_protocol.h"
#include <dlfcn.h>
#include <mach/mach.h>
#include <mach/mach_error.h>
#include <mach-o/dyld_images.h>
#include <objc/message.h>
#include <objc/runtime.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <sys/stat.h>

// mach_vm_* and libproc prototypes — headers aren't exported in iOS SDK.
extern kern_return_t mach_vm_allocate(vm_map_t, mach_vm_address_t *, mach_vm_size_t, int);
extern kern_return_t mach_vm_write(vm_map_t, mach_vm_address_t, vm_offset_t, mach_msg_type_number_t);
extern kern_return_t mach_vm_protect(vm_map_t, mach_vm_address_t, mach_vm_size_t, boolean_t, vm_prot_t);
extern kern_return_t mach_vm_read_overwrite(vm_map_t, mach_vm_address_t, mach_vm_size_t, mach_vm_address_t, mach_vm_size_t *);

#define PROC_PIDPATHINFO_MAXSIZE  (4 * 1024)
#define PROC_ALL_PIDS              1
extern int proc_pidpath(int pid, void *buffer, uint32_t buffersize);
extern int proc_listpids(uint32_t type, uint32_t typeinfo, void *buffer, int buffersize);

// Embedded helper dylib bytes (generated by the build).
#include "vphone_shake_dylib_data.h"

static void diag(const char *fmt, ...) __attribute__((format(printf, 1, 2)));

static BOOL deploy_helper_to(const char *path) {
    // Make sure parent dir exists (mkdir is idempotent — error on EEXIST is fine).
    char dirbuf[PATH_MAX];
    strlcpy(dirbuf, path, sizeof(dirbuf));
    char *slash = strrchr(dirbuf, '/');
    if (slash) {
        *slash = 0;
        mkdir(dirbuf, 0755);
    }
    FILE *fp = fopen(path, "wb");
    if (!fp) {
        diag("deploy: fopen %s failed: %s", path, strerror(errno));
        return NO;
    }
    size_t wrote = fwrite(vphone_shake_dylib, 1, vphone_shake_dylib_len, fp);
    fclose(fp);
    if (wrote != vphone_shake_dylib_len) {
        diag("deploy: short write %zu/%u", wrote, vphone_shake_dylib_len);
        return NO;
    }
    chmod(path, 0755);
    diag("deploy: wrote %u bytes to %s", vphone_shake_dylib_len, path);
    return YES;
}

// MARK: - Logging

static void diag(const char *fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    NSLog(@"[vphone_motion] %s", buf);
    FILE *fp = fopen("/tmp/vp_motion.log", "a");
    if (fp) { fprintf(fp, "%s\n", buf); fclose(fp); }
}

// MARK: - Shellcode
//
// thread_create_running creates a raw Mach thread without pthread state, so
// calling dlopen directly crashes inside pthread_getspecific. Bootstrap into
// pthread land with pthread_create_from_mach_thread, then call dlopen on
// the new pthread (which has TLS set up by the kernel via bsdthread_create).
//
// Layout in target's code page:
//   +0x00  OUTER  (Mach thread entry)
//   +0x40  INNER  (pthread entry)
//
// `args` struct (allocated separately, address passed in x0):
//   [0]   uint64 dlopen_addr            (raw target slid)
//   [8]   uint64 pthread_create_fn      (raw target slid)
//   [16]  uint64 inner_entry            (raw target slid)
//   [24]  uint64 path_ptr               (target memory)
__attribute__((naked, noinline, used))
static void shellcode_template(void) {
    asm volatile(
        // PAC mnemonics aren't in baseline arm64; enable for this block only.
        // On non-PAC CPUs the encoded bytes decode as NOP / plain BLR.
        ".arch_extension pauth  \n"
        // === OUTER ENTRY (offset 0) ===
        // x0 = args pointer.
        "mov  x19, x0           \n"   // save args
        "ldr  x20, [x0, #8]     \n"   // x20 = pthread_create_fn
        "ldr  x21, [x0, #16]    \n"   // x21 = inner_entry (raw)
        "paciza x21             \n"   // sign as function pointer (disc 0)
        "sub  sp, sp, #16       \n"   // pthread_t storage
        "mov  x0, sp            \n"
        "mov  x1, #0            \n"   // attr = NULL
        "mov  x2, x21           \n"   // start_routine (signed)
        "mov  x3, x19           \n"   // arg = args pointer
        "paciza x20             \n"   // sign pthread_create_fn
        "blraaz x20             \n"   // call pthread_create_from_mach_thread
        "add  sp, sp, #16       \n"
        "1:  b 1b               \n"   // park outer thread

        // Pad to inner entry at offset 0x40
        ".balign 64             \n"

        // === INNER ENTRY (offset 0x40) — runs on real pthread with TLS ===
        // x0 = args pointer (passed by pthread).
        "mov  x19, x0           \n"   // save args before clobbering x0
        "ldr  x16, [x19]        \n"   // dlopen address
        "ldr  x0,  [x19, #24]   \n"   // path
        "mov  x1,  #2           \n"   // RTLD_NOW
        "paciza x16             \n"
        "blraaz x16             \n"
        "str  x0,  [x19, #32]   \n"   // store dlopen handle (NULL on failure)
        "2:  b 2b               \n"   // park inner thread after constructor
    );
}
#define SHELLCODE_INNER_OFFSET   0x40
static const size_t kShellcodeSize = 0x40 + (8 * 4); // 0x40 + 32 = 96 bytes

struct shake_args {
    uint64_t dlopen_addr;
    uint64_t pthread_create_fn;
    uint64_t inner_entry;
    uint64_t path_ptr;
    uint64_t dlopen_result;   // written by inner shellcode
};

// MARK: - Shared cache slide

static uintptr_t get_self_shared_cache_slide(void) {
    // dyld_all_image_infos lives at a known address in our process.
    // task_info(self, TASK_DYLD_INFO) gives us its address.
    struct task_dyld_info info = {0};
    mach_msg_type_number_t count = TASK_DYLD_INFO_COUNT;
    if (task_info(mach_task_self(), TASK_DYLD_INFO, (task_info_t)&info, &count) != KERN_SUCCESS) {
        return 0;
    }
    if (!info.all_image_info_addr) return 0;
    const struct dyld_all_image_infos *aii =
        (const struct dyld_all_image_infos *)(uintptr_t)info.all_image_info_addr;
    return (uintptr_t)aii->sharedCacheSlide;
}

static uintptr_t get_target_shared_cache_slide(task_t task) {
    struct task_dyld_info info = {0};
    mach_msg_type_number_t count = TASK_DYLD_INFO_COUNT;
    if (task_info(task, TASK_DYLD_INFO, (task_info_t)&info, &count) != KERN_SUCCESS) {
        return 0;
    }
    if (!info.all_image_info_addr) return 0;

    // Read the dyld_all_image_infos struct from the target. We only need
    // sharedCacheSlide at offset 152 (v15+) — read enough bytes to cover it.
    uint8_t buf[256] = {0};
    mach_vm_size_t got = 0;
    kern_return_t kr = mach_vm_read_overwrite(
        task, info.all_image_info_addr, sizeof(buf), (mach_vm_address_t)buf, &got);
    if (kr != KERN_SUCCESS || got < 160) {
        diag("  read all_image_infos kr=%d got=%llu", kr, (unsigned long long)got);
        return 0;
    }
    uintptr_t slide = *(uintptr_t *)(buf + 152);
    return slide;
}

// MARK: - Bundle / container discovery

static NSString *bundle_id_for_pid(pid_t pid) {
    char path[PROC_PIDPATHINFO_MAXSIZE] = {0};
    if (proc_pidpath(pid, path, sizeof(path)) <= 0) return nil;
    NSString *execPath = [NSString stringWithUTF8String:path];
    NSString *appDir = execPath;
    while (appDir.length > 0 && ![appDir hasSuffix:@".app"]) {
        NSString *parent = appDir.stringByDeletingLastPathComponent;
        if ([parent isEqualToString:appDir] || parent.length == 0) return nil;
        appDir = parent;
    }
    NSBundle *bundle = [NSBundle bundleWithPath:appDir];
    return bundle.bundleIdentifier;
}

static NSString *data_container_for_bundle(NSString *bundleID) {
    if (!bundleID) return nil;
    Class wsCls = NSClassFromString(@"LSApplicationWorkspace");
    if (!wsCls) return nil;
    id ws = ((id(*)(Class, SEL))objc_msgSend)(wsCls, sel_registerName("defaultWorkspace"));
    NSArray *apps = ((NSArray *(*)(id, SEL))objc_msgSend)(
        ws, sel_registerName("allInstalledApplications"));
    for (id proxy in apps) {
        NSString *bid = [proxy valueForKey:@"bundleIdentifier"];
        if ([bid isEqualToString:bundleID]) {
            NSURL *url = [proxy valueForKey:@"dataContainerURL"];
            return url.path;
        }
    }
    return nil;
}

// MARK: - Foreground discovery via BKSApplicationStateMonitor

static int app_state_for_pid(pid_t pid) {
    Class cls = NSClassFromString(@"BKSApplicationStateMonitor");
    if (!cls) return -1;
    id monitor = ((id(*)(id, SEL))objc_msgSend)(
        ((id(*)(Class, SEL))objc_msgSend)(cls, sel_registerName("alloc")),
        sel_registerName("init"));
    if (!monitor) return -1;
    SEL sel = sel_registerName("mostElevatedApplicationStateForPID:");
    if (![monitor respondsToSelector:sel]) return -2;
    int state = ((int(*)(id, SEL, pid_t))objc_msgSend)(monitor, sel, pid);
    return state;
}

static BOOL is_app_path(const char *path) {
    return path && (strstr(path, "/Application/") != NULL ||
                    strstr(path, "/Applications/") != NULL);
}

// Pick the best injection target: user-app pid where task_for_pid works,
// preferring foreground-active state.
static pid_t pick_target_pid(NSMutableDictionary *r) {
    int npids_byte = proc_listpids(PROC_ALL_PIDS, 0, NULL, 0);
    int cap = npids_byte / (int)sizeof(pid_t) + 16;
    pid_t *pids = calloc(cap, sizeof(pid_t));
    int got_byte = proc_listpids(PROC_ALL_PIDS, 0, pids, cap * (int)sizeof(pid_t));
    int npids = got_byte / (int)sizeof(pid_t);

    pid_t best = 0;
    int bestState = INT_MIN;
    NSMutableArray *cands = [NSMutableArray array];

    for (int i = 0; i < npids; i++) {
        pid_t pid = pids[i];
        if (pid <= 1) continue;

        char path[PROC_PIDPATHINFO_MAXSIZE] = {0};
        if (proc_pidpath(pid, path, sizeof(path)) <= 0) continue;
        if (!is_app_path(path)) continue;
        // Skip plugin/extension processes — they end in `.appex/<name>`.
        if (strstr(path, ".appex/")) continue;

        // Filter by task_for_pid (drops system apps automatically).
        task_t task = MACH_PORT_NULL;
        if (task_for_pid(mach_task_self(), pid, &task) != KERN_SUCCESS) continue;
        // Don't keep the port; we'll re-fetch when actually injecting.
        mach_port_deallocate(mach_task_self(), task);

        int state = app_state_for_pid(pid);
        diag("  candidate pid=%d state=%d path=%s", pid, state, path);
        [cands addObject:@{@"pid": @(pid), @"state": @(state),
                           @"path": [NSString stringWithUTF8String:path]}];
        // Higher state value = more foreground-y in BKS enum.
        if (state > bestState) { bestState = state; best = pid; }
    }
    free(pids);

    r[@"candidates"] = cands;
    r[@"selected_pid"] = @(best);
    r[@"selected_state"] = @(bestState);
    return best;
}

// MARK: - Injection state (per-pid, to skip re-injection)

static NSMutableSet<NSNumber *> *gInjectedPids;

static BOOL is_injected(pid_t pid) {
    return [gInjectedPids containsObject:@(pid)];
}
static void mark_injected(pid_t pid) {
    if (!gInjectedPids) gInjectedPids = [NSMutableSet set];
    [gInjectedPids addObject:@(pid)];
}
static void unmark_injected(pid_t pid) {
    [gInjectedPids removeObject:@(pid)];
}

// MARK: - Mach injection

static BOOL inject_dylib(pid_t pid, const char *dylib_path, NSMutableDictionary *r) {
    task_t task = MACH_PORT_NULL;
    kern_return_t kr = task_for_pid(mach_task_self(), pid, &task);
    if (kr != KERN_SUCCESS) {
        diag("  task_for_pid pid=%d kr=%d (%s)", pid, kr, mach_error_string(kr));
        r[@"err"] = @"task_for_pid";
        r[@"kr"] = @(kr);
        return NO;
    }

    uintptr_t self_slide = get_self_shared_cache_slide();
    uintptr_t target_slide = get_target_shared_cache_slide(task);

    // Resolve the two shared-cache symbols we need. Both processes share the
    // same dyld cache layout — only the slide differs.
    uintptr_t self_dlopen = (uintptr_t)&dlopen;
    void *pthread_fn_local = dlsym(RTLD_DEFAULT, "pthread_create_from_mach_thread");
    if (!pthread_fn_local) {
        diag("  pthread_create_from_mach_thread symbol not found");
        r[@"err"] = @"sym_missing";
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }
    uintptr_t self_pthread = (uintptr_t)pthread_fn_local;

    uintptr_t target_dlopen  = self_dlopen  - self_slide + target_slide;
    uintptr_t target_pthread = self_pthread - self_slide + target_slide;
    diag("  slides self=0x%lx tgt=0x%lx", self_slide, target_slide);
    diag("  dlopen self=0x%lx tgt=0x%lx", self_dlopen, target_dlopen);
    diag("  pthread_create_from_mach_thread self=0x%lx tgt=0x%lx", self_pthread, target_pthread);

    // Allocate path page
    mach_vm_address_t path_addr = 0;
    size_t path_len = strlen(dylib_path) + 1;
    kr = mach_vm_allocate(task, &path_addr, 4096, VM_FLAGS_ANYWHERE);
    if (kr != KERN_SUCCESS) {
        diag("  alloc path kr=%d (%s)", kr, mach_error_string(kr));
        r[@"err"] = @"alloc_path"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }
    kr = mach_vm_write(task, path_addr, (vm_offset_t)dylib_path, (mach_msg_type_number_t)path_len);
    if (kr != KERN_SUCCESS) {
        diag("  write path kr=%d", kr);
        r[@"err"] = @"write_path"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }

    // Allocate + write code page
    mach_vm_address_t code_addr = 0;
    kr = mach_vm_allocate(task, &code_addr, 4096, VM_FLAGS_ANYWHERE);
    if (kr != KERN_SUCCESS) {
        diag("  alloc code kr=%d", kr);
        r[@"err"] = @"alloc_code"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }
    kr = mach_vm_write(task, code_addr, (vm_offset_t)&shellcode_template,
                       (mach_msg_type_number_t)kShellcodeSize);
    if (kr != KERN_SUCCESS) {
        diag("  write code kr=%d", kr);
        r[@"err"] = @"write_code"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }
    kr = mach_vm_protect(task, code_addr, 4096, FALSE, VM_PROT_READ | VM_PROT_EXECUTE);
    if (kr != KERN_SUCCESS) {
        diag("  protect code RX kr=%d (%s)", kr, mach_error_string(kr));
        r[@"err"] = @"protect_code"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }

    // Allocate + write args struct
    mach_vm_address_t args_addr = 0;
    kr = mach_vm_allocate(task, &args_addr, 4096, VM_FLAGS_ANYWHERE);
    if (kr != KERN_SUCCESS) {
        diag("  alloc args kr=%d", kr);
        r[@"err"] = @"alloc_args"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }
    struct shake_args args = {
        .dlopen_addr = target_dlopen,
        .pthread_create_fn = target_pthread,
        .inner_entry = (uint64_t)(code_addr + SHELLCODE_INNER_OFFSET),
        .path_ptr = (uint64_t)path_addr,
    };
    kr = mach_vm_write(task, args_addr, (vm_offset_t)&args, sizeof(args));
    if (kr != KERN_SUCCESS) {
        diag("  write args kr=%d", kr);
        r[@"err"] = @"write_args"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }

    // Allocate stack (16 KB)
    mach_vm_address_t stack_addr = 0;
    kr = mach_vm_allocate(task, &stack_addr, 16384, VM_FLAGS_ANYWHERE);
    if (kr != KERN_SUCCESS) {
        diag("  alloc stack kr=%d", kr);
        r[@"err"] = @"alloc_stack"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }

    diag("  code=0x%llx path=0x%llx args=0x%llx stack=0x%llx",
         (unsigned long long)code_addr,
         (unsigned long long)path_addr,
         (unsigned long long)args_addr,
         (unsigned long long)stack_addr);

    // Set up thread state and spawn
    arm_thread_state64_t state = {0};
    state.__x[0] = (uint64_t)args_addr;   // outer entry expects args ptr in x0
    __darwin_arm_thread_state64_set_pc_fptr(state, (void *)code_addr);
    __darwin_arm_thread_state64_set_sp(state, (void *)(stack_addr + 16384 - 256));

    thread_act_t thread = MACH_PORT_NULL;
    kr = thread_create_running(task, ARM_THREAD_STATE64,
                               (thread_state_t)&state, ARM_THREAD_STATE64_COUNT, &thread);
    if (kr != KERN_SUCCESS) {
        diag("  thread_create_running kr=%d (%s)", kr, mach_error_string(kr));
        r[@"err"] = @"thread_create_running"; r[@"kr"] = @(kr);
        mach_port_deallocate(mach_task_self(), task);
        return NO;
    }

    diag("  injected thread=0x%x into pid=%d", thread, pid);
    r[@"injected_thread"] = @(thread);
    r[@"injected"] = @YES;
    mach_port_deallocate(mach_task_self(), thread);
    mach_port_deallocate(mach_task_self(), task);
    return YES;
}

// MARK: - Load + entry point

static BOOL gLoaded = NO;

BOOL vp_motion_load(void) {
    if (gLoaded) return YES;

    // Need BKSApplicationStateMonitor for foreground filtering.
    dlopen("/System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices", RTLD_NOW);
    diag("vp_motion_load: ready (per-container deploy)");

    gLoaded = YES;
    return YES;
}

BOOL vp_motion_available(void) {
    return gLoaded;
}

NSDictionary *vp_handle_motion_command(NSDictionary *msg) {
    id reqId = msg[@"id"];
    NSMutableDictionary *r = vp_make_response(@"ok", reqId);

    if (!gLoaded) {
        NSMutableDictionary *err = vp_make_response(@"err", reqId);
        err[@"msg"] = @"motion not loaded";
        return err;
    }

    pid_t pid = pick_target_pid(r);
    if (pid <= 0) {
        NSMutableDictionary *err = vp_make_response(@"err", reqId);
        err[@"msg"] = @"no injectable foreground app (no dev-signed user app with task_for_pid access)";
        return err;
    }
    diag("  target pid=%d", pid);

    if (is_injected(pid)) {
        // Repeat shake: just signal the existing helper.
        diag("  already injected; sending SIGUSR2");
        if (kill(pid, SIGUSR2) != 0) {
            diag("  kill SIGUSR2 failed errno=%d, will re-inject", errno);
            unmark_injected(pid);
        } else {
            r[@"method"] = @"signal";
            return r;
        }
    }

    // Deploy helper to the target's own data container — that's the only
    // path guaranteed readable by a sandboxed app.
    NSString *bid = bundle_id_for_pid(pid);
    NSString *container = data_container_for_bundle(bid);
    diag("  target bundle=%s container=%s",
         bid.UTF8String ?: "?", container.UTF8String ?: "?");
    if (!container) {
        NSMutableDictionary *err = vp_make_response(@"err", reqId);
        err[@"msg"] = @"could not resolve target data container";
        return err;
    }
    NSString *dylibPath = [container stringByAppendingPathComponent:@"tmp/vphone_shake.dylib"];
    if (!deploy_helper_to(dylibPath.fileSystemRepresentation)) {
        NSMutableDictionary *err = vp_make_response(@"err", reqId);
        err[@"msg"] = @"deploy to container failed";
        return err;
    }

    if (!inject_dylib(pid, dylibPath.fileSystemRepresentation, r)) {
        NSMutableDictionary *err = vp_make_response(@"err", reqId);
        err[@"msg"] = @"injection failed";
        err[@"detail"] = r;
        return err;
    }
    mark_injected(pid);
    // Constructor only installs the SIGUSR2 handler; fire the actual shake
    // via the signal path. Covers both fresh loads and cached re-dlopen
    // (e.g. vphoned restarted but the helper is still resident in target).
    if (kill(pid, SIGUSR2) != 0) {
        diag("  post-inject SIGUSR2 failed errno=%d", errno);
    }
    r[@"method"] = @"inject";
    return r;
}
